articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
#name space the file
#ajuda o django a saber onde está o 'name' que eu quero que ele encontre

urlpatterns = [
    #adicionei a página lista de artigos + indiquei a função que será executada quando alguém
    #pedir a rota da lista de artigos
    #minhas URLS são nomeadas pra not hard code the url in href
    path('', views.article_list, name='list'),
    path('<slug:slug>/', views.article_detail, name='detail'),
    #<slug:slug> is a name capturing group (2º slug poderia ser qualquer outro nome)
    #1º slug is type of the parameter
    #2º slug is the name of the parameter
]

djangonautic/urls.py
#meu path é o url dele
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#let us append to the URL pattern so that Django can handle the serving goal

urlpatterns = [
    path('admin/', admin.site.urls),
    #adicionei a página about + indiquei a função que será executada quando alguém
    #pedir a rota about
    path('about/', views.about),
    #adicionei a home page
    path('', views.homepage),
    #o include vai fazer com que o Django olhe dentro do urls.py do articles app
    path('articles/', include('articles.urls')),
]

urlpatterns += staticfiles_urlpatterns()
#check if we are in debug mode, then append here to serve the static file

articles/models.py
from django.db import models
from django.db.models.fields import CharField
from django.urls.converters import SlugConverter

# Create your models here.

class Article(models.Model):
    #porque models? porque os tipos estão DENTRO dela
    #estou acessando por notação de ponto
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    #add in thumbnail later
    #add in author later

    #como o obj vai aparecer no admin ou no shell
    def __str__(self):
        return self.title
    #<QuerySet [<Article: Article object (1)>]>
    #<QuerySet [<Article: article title str name>]>

    def snippet(self):
        return self.body[:50] + '...'

articles/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Article
#importar o Article para exibir os objs => articles

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    #coleta todos os obj da table Article + organiza por data (.order_by('forma de organizar'))
    #usando o .models (ORM)!!!
    return render(request, 'articles/article_list.html', {
        'articles': articles
    })
    #add a 3º parameter to the render function
    #the data is what will be sent to the view or the template(!)
    #é um dict que será enviado ao template (html file) com o que acabou
    #de ser recebido em articles na linha 7

    #vou renderizar esses artigos aqui da view,
    #que foram buscados lá da DB da models
    #lá pra article_list.html

def article_detail(request, slug):
    # return HttpResponse(slug)
    #captura para onde o user quer ir e joga dentro da função
    #e retorna na tela o slug pro user ver

    #query the data base e get a ARTICLE TO OUTPUT
    article = Article.objects.get(slug=slug)
    #the slug paramenter has to be equal the slug we get here
    return render(request, 'articles/article_detail.html', { 'article': article})
    #1º request, 2º template to render, 3º dados (dict) // prop = o article da var

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    #return HttpResponse('about')
    return render(request, 'about.html')

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

<!--Esse bloco vai ser disparado pro user pela def article_detail
    da views do articles
-->

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Article List</h1>
    <div class='articles'>
        <!--
        Templates tags do python em curly braces => 
        %python code: for%} // {data: info do DB}}
        Como não sei quantos artigos terei, usarei um for + template tag
        o for se refere ao views.py linha 10, 3º parameter as a dict
        Para cada um dos artigos que forem renderizados aqui, lá da views
        será exibido um div com um h2 e 2 p's com informações do title,
        do body e do date (properties)
        -->
        {% for article in articles %}
            <div class='article'>
                <h2><a href="{% url 'articles:detail' article.slug %}">{{ article.title }}</a></h2>
                <!--use a url in the articles name space, that is called detail
                como essa url pede um slug, use o do article.slug e jogue na função
                article_detail
                -->
                <p>{{ article.snippet }}</p>
                <p>{{ article.date }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
</head>
<body>
    <h1>About Us</h1>
    <p>We like Django</p>
</body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="wrapper">
        <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png' %}"></a></h1>
        <!--use a url in the articles name space, that is called list
        -->
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    <h1>This is the homepage</h1>
    <p>Welcome to Djangonautic</p>
</body>
</html>